# Generated by Django 3.2.12 on 2022-03-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='posts/thumbnails/real14.jpg', upload_to='posts/thumbnails/'),
        ),
    ]
