# Generated by Django 3.2.12 on 2022-03-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_account_active'),
        ('posts', '0006_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
