# Generated by Django 3.2.12 on 2022-03-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_account_active'),
        ('posts', '0008_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to='accounts.Account'),
        ),
    ]
