# Generated by Django 3.2.12 on 2022-03-13 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='correct_answer',
            field=models.CharField(choices=[('1', 'Answer_1'), ('2', 'Answer_2')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(choices=[('1', 'Answer_1'), ('2', 'Answer_2')], max_length=1)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
