# Generated by Django 3.2.12 on 2022-03-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220314_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answers',
        ),
    ]
