# Generated by Django 3.2.12 on 2022-03-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points_wagered',
            field=models.IntegerField(default=0),
        ),
    ]
