# Generated by Django 3.2.12 on 2022-03-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_alltime_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='alias',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
