# Generated by Django 3.2.12 on 2022-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(default='default-user.png', upload_to='account/'),
        ),
    ]
