# Generated by Django 3.2.12 on 2022-03-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220310_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alltime_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
