# Generated by Django 3.2.12 on 2022-03-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_alltime_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alltime_points',
            field=models.IntegerField(default=0),
        ),
    ]
