# Generated by Django 3.2.12 on 2022-03-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_alltime_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(default='account/default-user.png', upload_to='account/'),
        ),
    ]
