# Generated by Django 3.2.12 on 2022-03-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_account_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
    ]
