# Generated by Django 3.2.12 on 2022-03-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_account_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
