# Generated by Django 3.2.12 on 2022-03-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_account_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alltime_points',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='points',
            field=models.IntegerField(default=1000),
        ),
    ]
